export const LABELS = {
  addNewUser: 'Nowy użytkownik',
  areYouSure: 'Jesteś pewien?',
  cancel: 'cofnij',
  delete: 'usuń',
  edit: 'edytuj',
  email: 'Email',
  emailRequired: 'Należy podać email',
  fillActiveWarning: 'Uzupełnij lub usuń aktualnie dodawanego użytkownika',
  name: 'Imię i nazwisko',
  nameRequired: 'Należy podać imię i nazwisko',
  newUser: 'Nowy użytkownik',
  no: 'nie',
  optionalIndex: 'Indeks studenta (opcjonalnie)',
  requiredField: 'Pole jest wymagane',
  role: 'Rola użytkownika',
  roleRequired: 'Należy podać rolę użytkownika',
  save: 'zapisz',
  searchByRolePlaceholder: 'Szukaj według roli użytkownika',
  searchUserPlaceholder: 'Szukaj według imienia, nazwiska lub indeksu',
  upload: 'CSV upload',
  yes: 'tak',
};
