export const LABELS = {
  addNewUser: 'Nowy użytkownik',
  areYouSure: 'Jesteś pewien?',
  cancel: 'cofnij',
  classDay: 'Dzień zajęć',
  classDayRequired: 'Należy podać dzien zajęć',
  classRoomNumber: 'Numer sali',
  classRoomNumberRequired: 'Należy podać numer sali',
  classTime: 'Godzina zajęć',
  classTimeRequired: 'Należy podać godzinę zajęć',
  delete: 'usuń',
  edit: 'edytuj',
  email: 'Email',
  emailRequired: 'Należy podać email',
  fillActiveWarning: 'Uzupełnij lub usuń aktualnie dodawanego użytkownika',
  name: 'Imię i nazwisko',
  nameRequired: 'Należy podać imię i nazwisko',
  newUser: 'Nowy użytkownik',
  no: 'nie',
  optionalIndex: 'Indeks studenta (opcjonalnie)',
  requiredField: 'Pole jest wymagane',
  role: 'Rola użytkownika',
  roleRequired: 'Należy podać rolę użytkownika',
  save: 'zapisz',
  searchByRolePlaceholder: 'Szukaj według roli użytkownika',
  searchUserPlaceholder: 'Szukaj według imienia, nazwiska lub indeksu',
  semester: 'Semestr',
  semesterRequired: 'Należy podać semestr',
  superUser: 'Prowadzący',
  upload: 'CSV upload',
  weekdays: ['poniedziałek', 'wtorek', 'środa', 'czwartek', 'piątek'],
  yearRequired: 'Należy podać rok akademicki',
  yes: 'tak',
};
