export const LABELS = {
  addNewUser: 'Nowy użytkownik',
  areYouSure: 'Jesteś pewien?',
  cancel: 'cofnij',
  delete: 'usuń',
  edit: 'edytuj',
  fillActiveWarning: 'Uzupełnij lub usuń aktualnie dodawanego użytkownika',
  no: 'nie',
  requiredField: 'Pole jest wymagane',
  save: 'zapisz',
  searchByRolePlaceholder: 'Szukaj według roli użytkownika',
  searchUserPlaceholder: 'Szukaj według imienia, nazwiska lub indeksu',
  upload: 'CSV upload',
  yes: 'tak',
};
