// tslint:disable:no-hardcoded-credentials
export const LABELS = {
  add: 'Dodaj',
  addNewUser: 'Nowy użytkownik',
  appName: 'Lagrange',
  areYouSure: 'Jesteś pewien?',
  assignment: 'Pracownia',
  cancel: 'anuluj',
  classDay: 'Dzień ćwiczeń',
  classDayRequired: 'Należy podać dzień ćwiczeń',
  classTime: 'Godzina pracowni',
  classTimeRequired: 'Należy podać godzinę pracowni',
  classroomNumber: 'Numer sali',
  classroomNumberRequired: 'Należy podać numer sali',
  confirmPassword: 'Potwierdź hasło',
  delete: 'usuń',
  edit: 'edytuj',
  email: 'Email',
  emailRequired: 'Należy podać email',
  equationCantBeEmpty: 'Równanie nie może być puste',
  exercise: 'Ćwiczenia',
  fillActiveWarning: 'Uzupełnij lub usuń aktualnie dodawanego użytkownika',
  forgotPassword: 'Nie pamiętasz hasła?',
  goToLoginPage: 'Przejdź do logowania',
  group: 'Rodzaj grupy',
  groupName: 'Nazwa grupy',
  groupNameRequired: 'Nazwa grupy jest wymagana',
  groupRequired: 'Rodzaj grupy jest wymagany',
  homework: 'Zadanie domowe',
  index: 'Indeks studenta',
  lab: 'Pracownia',
  labDay: 'Dzień pracowni',
  labDayRequired: 'Należy podać dzien pracowni',
  labRoomNumber: 'Numer sali',
  labRoomNumberRequired: 'Należy podać numer sali',
  labTime: 'Godzina pracowni',
  labTimeRequired: 'Należy podać godzinę pracowni',
  lecture: 'Wykład',
  lecturer: 'Prowadzący',
  logIn: 'Zaloguj się',
  magicLinkInvalid: 'Link wygasł lub jest niepoprawny',
  name: 'Imię i nazwisko',
  nameRequired: 'Należy podać imię i nazwisko',
  newGroup: 'Nowa grupa',
  newUser: 'Nowy użytkownik',
  no: 'nie',
  noPrivilegesToUseApp: 'Brak uprawnień do korzystania z aplikacji',
  optionalIndex: 'Indeks studenta (opcjonalnie)',
  password: 'Hasło',
  passwordRequired: 'Należy podać hasło',
  rememberMe: 'Pamiętaj mnie',
  requiredField: 'Pole jest wymagane',
  role: 'Rola użytkownika',
  roleRequired: 'Należy podać rolę użytkownika',
  save: 'Zapisz',
  searchByRolePlaceholder: 'Szukaj według roli użytkownika',
  searchUserPlaceholder: 'Szukaj według imienia, nazwiska lub indeksu',
  selectFromList: 'Wybierz z listy',
  selectFromListOrCreate: 'Wybierz z listy lub wprowadź dane',
  semester: 'Semestr',
  semesterRequired: 'Należy podać semestr',
  serverUnavaliable: 'Serwer jest niedostępny, spróbuj ponownie później',
  setNewPassword: 'Ustaw hasło do swojego konta.',
  superUser: 'Prowadzący',
  upload: 'CSV upload',
  weekdays: ['poniedziałek', 'wtorek', 'środa', 'czwartek', 'piątek'],
  yearRequired: 'Należy podać rok akademicki',
  yes: 'tak',
};
